### ISSUE TITLE
grid mapping variable = "crs" for all projections (Lambert_Conformal, Mercator, etc.) 

### ISSUE THREAD

**Issue by gnikulin** [HCLIMcom/HCLIM2CMOR#24]
We need:

- to rename the grid mapping variable from `Lambert_Conformal` to `crs`
- to change the variable attribute `grid_mapping` from `Lambert_Conformal` to `crs`

In general, it would be good to make the above changes for other projections, e.g.  if `Mercator` is used. 

@doblerone as I remember you use the polar stereographic projection for the Arctic region ?

**Comment by doblerone** [comment]
Yes, both Arctic and Antarctic are polar stereographic because rotated Mercator is not supported in our surfex setup.

**Comment by gnikulin** [comment]
how the grid mapping variable is named in your output files ? It's better to code all current projections that should be renamed to `crs`

**Comment by doblerone** [comment]
char Polar_Stereographic ;
		Polar_Stereographic:grid_mapping_name = "polar_stereographic" ;
		Polar_Stereographic:straight_vertical_longitude_from_pole = 0. ;
		Polar_Stereographic:latitude_of_projection_origin = 90. ;
		Polar_Stereographic:standard_parallel = 90. ;
		Polar_Stereographic:false_easting = 3342789.78413246 ;
		Polar_Stereographic:false_northing = 3701378.25579671 ;
		Polar_Stereographic:earth_radius = 6371229. ;
		Polar_Stereographic:proj4 = "+proj=stere +lat_0=90.000000 +lat_ts=90.000000 +lon_0=.000000 +k_0=1.0 +x_0=3342789.784132 +y_0=3701378.255797 +a=6371229.000000 +b=6371229.000000" ;

**Comment by gnikulin** [comment]
Perhaps, we can hardcode that if he grid mapping variable is equal to `Lambert_Conformal` or `Mercator` or `Polar_Stereographic` rename it to `crs`, the same for the variable attribute `grid_mapping`

**Comment by ljoakim** [comment]
Listening in: @ljoakim

**Comment by ljoakim** [comment]
```
> char Polar_Stereographic ;
> 	Polar_Stereographic:grid_mapping_name = "polar_stereographic" ;
> 	Polar_Stereographic:straight_vertical_longitude_from_pole = 0. ;
> 	Polar_Stereographic:latitude_of_projection_origin = 90. ;
> 	Polar_Stereographic:standard_parallel = 90. ;
> 	Polar_Stereographic:false_easting = 3342789.78413246 ;
> 	Polar_Stereographic:false_northing = 3701378.25579671 ;
> 	Polar_Stereographic:earth_radius = 6371229. ;
> 	Polar_Stereographic:proj4 = "+proj=stere +lat_0=90.000000 +lat_ts=90.000000 +lon_0=.000000 +k_0=1.0 +x_0=3342789.784132 +y_0=3701378.255797 +a=6371229.000000 +b=6371229.000000" ;
```

I noticed this is not (exactly) the same list of attributes as for `Lambert_Conformal`. What would be the corresponding list of attributes for `Mercator`?

**Comment by gnikulin** [comment]
In our first tests for Africa we have:

```
char Mercator ;
     Mercator:grid_mapping_name = "mercator" ;
     Mercator:longitude_of_projection_origin = 18. ;
     Mercator:standard_parallel = 0. ;
     Mercator:proj4 = "+proj=merc +lat_ts=.000000 +lon_0=18.000000 +k_0=1.0" ;
 ```
We are missing  `false_easting` and `false_northing`, although these 2 parameters are optional ([CF-1.11](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.11/cf-conventions.html#_mercator)).

I think @larsbarring is a good expert in the Mercator projection :-).

**Comment by larsbarring** [comment]
I suggest you should [must] **not** use CF-1.11 (or earlier) as a reference for what to do (or not to do) with respect to coordinate reference systems (CRS). If you only look at the [Mercator](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.11/cf-conventions.html#_mercator) section you may come to the conclusion that what you have is what is needed (under the assumption that both `false_easting`and `false_northing` is 0.0). But you also need to consider what is written in the [introductory section of Appendix F](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.11/cf-conventions.html#_mercator), which states (among other things) that 
>Since the attributes used to set a mapping’s parameters may be shared among several mappings, their definitions are contained in a table in the final section. The attributes which describe the ellipsoid and prime meridian may be included, when applicable, with any grid mapping. These are: 
... ... ...

The question is then whether you need to specify the shape of the earth (ellipsoid, or otherwise), and the answer is indeed **yes**, cf. [OGP-EPSG_GN7_2](https://drive.tiny.cloud/1/4m326iu12oa8re9cjiadxonharclteqb4mumfxj71zsttwkx/abf43270-46c7-4875-9f45-1316e58c5233), and in particular [this section](https://drive.tiny.cloud/1/4m326iu12oa8re9cjiadxonharclteqb4mumfxj71zsttwkx/abf43270-46c7-4875-9f45-1316e58c5233#%5B%7B%22num%22%3A97%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C68%2C745%2C0%5D). If you, like me, do not want to dig into the equations an alternative good source is the [`proj` documentation](https://proj.org) and its section on the [Mercator projection](https://proj.org/en/9.4/operations/projections/merc.html). This section list all the relevant parameters for the Mercator projection (both spherical and elliptical), and provides default values for all except `+R` (radius of the sphere), which is an alternative specification to the default `ellps`. 

Thus, if you do not provide such information it totally depends on what software you you are using. `Proj`will use `GRS80` as default for the Mercator projection, many other tools will use `WGS84`, (e.g Cartopy I think). Some tools may even use the unit sphere, which will give totally ridiculous results. 

*That is, you need to specify the shape of the earth.* 

With respect to CF appendix F, this advice applies to all map projections except `Latitude-longitude` and  `Rotated pole`.

BTW, the `proj` library is now at version 9.4 (proj4 is since long outdated, even though there are only marginal changes to the parameter specs), see [here](https://github.com/cf-convention/discuss/issues/43) for a related CF conversation.

**Comment by ljoakim** [comment]
Thanks for the answers, good advice, I think the comments from @larsbarring  are relevant for the data production.

For the sake of this issue, the reason I was asking is that [the transfer/reformatting of the crs attributes from the input file to the output](https://github.com/HCLIMcom/HCLIM2CMOR/blob/1134dc07d049422f4923515a635471bda7d5ab0c/src/CMORlight/tools.py#L574) (called e.g. [here](https://github.com/HCLIMcom/HCLIM2CMOR/blob/1134dc07d049422f4923515a635471bda7d5ab0c/src/CMORlight/tools.py#L1475)) currently only supports `Lambert_Conformal`. The transfer of `Polar_Stereographic` and `Mercator` needs to be similarly coded, unless a straight copy of all attributes are fine. I assume the list of `Polar_Stereographic` attributes are fine, but the list of attributes for `Mercator` given above then is incomplete. This should probably be fixed already in the "raw"/"pre-cmorized" data, but regardless, a complete list of attributes are needed. 

@gnikulin: can the `false_easting` and `false_northing` be added in the simulation output and proj string (even if they are 0.0, it's better to be verbose (?)). Is there information about the earth shape that can be added?

**Comment by gnikulin** [comment]
Yes, we need to fix all coordinate-related attributes already in the "raw"/"pre-cmorized" data. 

- @AitorAldama I took the above example with the Mercator projection from our Africa test runs. Can we also add `false_easting` and `false_northing` similar to the LCC and Polar Stereographic projections?
- we need to check the earth shape used for the Mercator projection by HCLIM

**Comment by AitorAldama** [comment]
Hej @gnikulin,

I did add the `false easting` and `false northing` for Mercator projection in HCLIM. I added them when I merged the changes to the HCLIM43_develop branch. See the discussion of the pull request for details ([Pull request #108 HCLIM](https://github.com/Hirlam/HCLIM/pull/108)).

The test runs we did for Africa are prior to these changes therefore the `false easting` and `false northing` are not included in the netCDF files.

**Comment by AitorAldama** [comment]
Hej @gnikulin,

This is an example of the metadata written on the netcdf file by gl for a mercator projection (same domain as in the pull request):

```
char Mercator ;
		Mercator:grid_mapping_name = "mercator" ;
		Mercator:longitude_of_projection_origin = 31. ;
		Mercator:standard_parallel = 0. ;
		Mercator:false_easting = 1100000. ;
		Mercator:false_northing = -1772629.97757293 ;
		Mercator:earth_radius = 6371229. ;
		Mercator:proj4 = "+proj=merc +lat_ts=.000000 +lon_0=31.000000 +k_0=1.0 +x_0=1100000.000000 +y_0=-1772629.977573 +a=6371229.000000 +b=6371229.000000" ;
```
You can find the example file [here (mercator_example.nc.zip)](https://github.com/HCLIMcom/HCLIM2CMOR/files/15344673/mercator_example.zip)

**Comment by larsbarring** [comment]
Ok, so all information already easily available to use and transfer in the right format. That should simplify things. 

I would suggest that it is useful, and future-proof, to also include the `proj4` attribute, but change attribute name. Unfortunately, this is not yet in CF, although there is a [suggestion](https://github.com/cf-convention/discuss/issues/43) that for now has lost traction. And, Iris is not yet up to this, see [here](https://github.com/SciTools/iris/discussions/5560).

**Comment by ljoakim** [comment]
Starting to look into this, two questions:
1. If a coordinate file is specified, apart from `['Lambert_Conformal', 'Mercator', 'Polar_Stereographic']`, should I expect it could contain a crs variable already renamed to `crs`, instead of the previous three?
2. I think it will be easier to make a straight copy of the crs variable (only rename it to `crs`). Can I assume it's ok to do this for all crs types, regardless of data source?

**Comment by gnikulin** [comment]
>     1. If a coordinate file is specified, apart from `['Lambert_Conformal', 'Mercator', 'Polar_Stereographic']`, should I expect it could contain a crs variable already renamed to `crs`, instead of the previous three?

Yes, `crs` can be expected  as it is now one of the CORDEX-CMIP6 standards. I would say even that if we create a coordinate file we must use `crs` as the name for the coordinate system variable. 
 
>     2. I think it will be easier to make a straight copy of the crs variable (only rename it to `crs`). Can I assume it's ok to do this for all crs types, regardless of data source?

I think yes, because the coordinate file should be carefully prepared meaning 100% consistency with all standards and if we use `crs` in the coordinate file it's simply a copy.

**Comment by ljoakim** [comment]
> > ```
> > 2. I think it will be easier to make a straight copy of the crs variable (only rename it to `crs`). Can I assume it's ok to do this for all crs types, regardless of data source?
> > ```
> 
> 
> I think yes, because the coordinate file should be carefully prepared meaning 100% consistency with all standards and if we use `crs` in the coordinate file it's simply a copy.

I'm also thinking of the case where no coordinate file is specified, and the coordinate data is kept from the source file. Is there any special care that needs to be taken there, or is copy/rename fine?

**Comment by gnikulin** [comment]
As I see now we have full description of the coordinate system in the source file so copy/rename should be fine. We need to change all names to `crs` for future activities, e.g. CORDEX-Africa.
